version: 1.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
build:
  project: SimpleBackupService.sln
  parallel: true
  verbosity: minimal
artifacts:
- path: SimpleBackupService.Installer\bin\Release\*.msi
